name: Build Binary

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build Rust binary in release mode
        run: cargo build --release

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-binary
          path: target/release/main
